# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    ip_whitelist:
#        - 127.0.0.1
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        digits: 6
        enabled: true
        sender_email: hello@demomailtrap.com
        sender_name: TaskLinker Authentication
        template: 2FA/2fa_form.html.twig
        mailer: App\Security\MyAuthCodeMailer
    two_factor_condition: App\Security\TwoFactor\MyTwoFactorCondition
