controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: en|fr

switch_language:
    path: /switch-language/{locale}
    controller: App\Controller\LanguageController::switchLanguage
    requirements:
        locale: en|fr